# Generated by Django 2.2 on 2021-03-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210304_0634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-timestamp', '-updated']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
